name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      # スキーム/プロジェクト情報を確認（失敗原因の切り分け用）
      - name: Show Xcode projects & schemes
        run: |
          echo "Projects:" && ls -1 *.xcodeproj || true
          echo "Workspaces:" && ls -1 *.xcworkspace || true
          xcodebuild -list -json || true

      - name: Build (project)
        run: |
          xcodebuild \
            -project StudyRecord.xcodeproj \
            -scheme StudyRecord \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_ALLOWED=NO \
            build

