name: iOS CI

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -s "/Applications/Xcode_15.4.app/Contents/Developer"

      - name: Show available iOS runtimes
        run: xcrun simctl list runtimes | grep "iOS"

      - name: Resolve Swift Package dependencies
        run: xcodebuild -resolvePackageDependencies -project "StudyRecord.xcodeproj"

      - name: Build (iPhone 15 / iOS 17.5)
        run: |
          xcodebuild \
            -project "StudyRecord.xcodeproj" \
            -scheme "StudyRecord" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -configuration Debug \
            clean build
